#! /bin/sh

### START SETUP SXHKD ###
SXHKD_FIFO_DIR="$HOME/.cache/sxhkd"

if [ ! -d "$SXHKD_FIFO_DIR" ]; then
    mkdir -p "$SXHKD_FIFO_DIR"
fi

SXHKD_FIFO="$SXHKD_FIFO_DIR/status.fifo"

if [ ! -e "$SXHKD_FIFO" ]; then
    mkfifo "$SXHKD_FIFO"
fi

pgrep -x sxhkd > /dev/null || sxhkd -s "$SXHKD_FIFO" &
### END SETUP SXHKD ###

CONF_ROOT="$HOME/.config/bspwm"

xsetroot -cursor_name left_ptr & # force-show cursor

bspc monitor -d . . . . . . . .

bspc config border_width            3
bspc config window_gap             12
bspc config focused_border_color   "#f77065"
bspc config normal_border_color    "#131519"
bspc config active_border_color    "#131519"
bspc config presel_feedback_color  "#131519"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
. $CONF_ROOT/generated_rules

# Modifier key used with the mouse (usually Alt or Super)
bspc config pointer_modifier super

# Mouse actions while holding the modifier
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

wmname LG3D &

feh --bg-scale .wallpaper.png
xrdb ~/.Xresources
$CONF_ROOT/scripts/autostart-onedrive.sh &
nm-applet &
picom &

$CONF_ROOT/scripts/sxhkd-status.sh &
polybar &
