#! /bin/sh

### START SETUP SXHKD ###
SXHKD_FIFO_DIR="$HOME/.cache/sxhkd"

if [ ! -d "$SXHKD_FIFO_DIR" ]; then
    mkdir -p "$SXHKD_FIFO_DIR"
fi

SXHKD_FIFO="$SXHKD_FIFO_DIR/status.fifo"

if [ ! -e "$SXHKD_FIFO" ]; then
    mkfifo "$SXHKD_FIFO"
fi

pgrep -x sxhkd > /dev/null || sxhkd -s "$SXHKD_FIFO" &
### END SETUP SXHKD ###

xsetroot -cursor_name left_ptr & # force-show cursor

bspc monitor -d . . . .

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale .wallpaper.png
xrdb ~/.Xresources
./scripts/autostart-onedrive.sh &
nm-applet &
picom &

~/.config/bspwm/scripts/sxhkd-status.sh &
polybar &
