Section "Input Class"                                                                                     
        Identifier "/dev/input/event10"                                                                   
        Driver "libinput"                                                                                 
        Option "Tapping" "on"                                                                             
        Option "NaturalScrolling" "true"                                                                  
EndSection
