#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

source ./keybinds
source ./style
source ./rules
source ./startup

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
for monitor in $(polybar -m | sed -e 's/:.*$//g') ; do
    # start it on each monitor
    MONITOR=$monitor polybar -c ~/.config/polybar/conf/simple/config.ini &
done
