#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

HBWM="$HOME/.config/herbstluftwm"

hc emit_hook reload

source "$HBWM/keybinds"
source "$HBWM/style"
source "$HBWM/rules"
source "$HBWM/startup"

# unlock, just to be sure
hc unlock
