#!/usr/bin/env bash

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

TERMINAL=kitty

sys_notify="$HOME/.config/wired/sys_notify/sys_notify.sh"

# remove all existing keybindings
hc keyunbind --all

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback

# basic movement in tiling and floating mode
# focusing clients
# hc keybind $Mod-Left  focus left
# hc keybind $Mod-Down  focus down
# hc keybind $Mod-Up    focus up
# hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# custom
hc keybind $Mod-d spawn rofi -show drun -config ~/.config/rofi/conf/simple/config.rasi 
hc keybind $Mod-n spawn i3lock -i .wallpaper.png --time-str="%H:%M:%S" --date-str="" --time-pos="x+w/2:y+350" --time-color=ffffffff --clock --time-font=Bahnschrift --time-size=64
hc keybind $Mod-s spawn flameshot gui
hc keybind $Mod-Shift-c spawn bash -c "xcolor | tr -d '\n' | xclip -selection clipboard"

# --- Brightness Control ---
# Increase Brightness
hc keybind XF86MonBrightnessUp   spawn sh -c "brightnessctl set +10% && $sys_notify backlight"
# Decrease Brightness
hc keybind XF86MonBrightnessDown spawn sh -c "brightnessctl set 10%- && $sys_notify backlight"
# --- PipeWire Volume Control (via wpctl) ---
# Mute/Unmute (Targets the default audio output)
hc keybind XF86AudioMute         spawn sh -c "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $sys_notify audio_out"

# Mute/Unmute mic
hc keybind XF86AudioMicMute      spawn sh -c "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && $sys_notify audio_in"

# Lower Volume (Steps of 5%)
hc keybind XF86AudioLowerVolume  spawn sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && $sys_notify audio_out"

# Raise Volume (Steps of 5%, capped at 100% usually)
hc keybind XF86AudioRaiseVolume  spawn sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0 && $sys_notify audio_out"

# mouse

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
